//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.API.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identity.API.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application not found!.
        /// </summary>
        internal static string exception_AspNetApplicationNotFound {
            get {
                return ResourceManager.GetString("exception_AspNetApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role not exist!.
        /// </summary>
        internal static string exception_AspNetRoleNotFound {
            get {
                return ResourceManager.GetString("exception_AspNetRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not found.!.
        /// </summary>
        internal static string exception_AspNetUserNotFound {
            get {
                return ResourceManager.GetString("exception_AspNetUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad Request!!!.
        /// </summary>
        internal static string exception_BadRequest {
            get {
                return ResourceManager.GetString("exception_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email should not be empty!.
        /// </summary>
        internal static string exception_EmailNotNull {
            get {
                return ResourceManager.GetString("exception_EmailNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format email not valid..
        /// </summary>
        internal static string exception_FormatEmailNotValid {
            get {
                return ResourceManager.GetString("exception_FormatEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password should not be empty!.
        /// </summary>
        internal static string exception_PasswordNotNull {
            get {
                return ResourceManager.GetString("exception_PasswordNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password should contain at least one lower case letter, one upper case letter, should not be less than or greater than 12 characters should contain At least one numeric value and one special case characters..
        /// </summary>
        internal static string exception_PasswordNotValid {
            get {
                return ResourceManager.GetString("exception_PasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role Delete Failed..
        /// </summary>
        internal static string exception_RoleDeleteFailed {
            get {
                return ResourceManager.GetString("exception_RoleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role not exists!..
        /// </summary>
        internal static string exception_RoleNotExists {
            get {
                return ResourceManager.GetString("exception_RoleNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role Registration Failed..
        /// </summary>
        internal static string exception_RoleRegistrationFailed {
            get {
                return ResourceManager.GetString("exception_RoleRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Registration Failed..
        /// </summary>
        internal static string exception_UserRegistrationFailed {
            get {
                return ResourceManager.GetString("exception_UserRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are logged out!..
        /// </summary>
        internal static string message_Logout {
            get {
                return ResourceManager.GetString("message_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role Deleted!..
        /// </summary>
        internal static string message_RoleDeleteSuccessful {
            get {
                return ResourceManager.GetString("message_RoleDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role Registration Successful..
        /// </summary>
        internal static string message_RoleRegistrationSuccessful {
            get {
                return ResourceManager.GetString("message_RoleRegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Asigned To Role Successful..
        /// </summary>
        internal static string message_UserAsignedToRoleSuccessful {
            get {
                return ResourceManager.GetString("message_UserAsignedToRoleSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Deleted!..
        /// </summary>
        internal static string message_UserDeleteSuccessful {
            get {
                return ResourceManager.GetString("message_UserDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Registration Successful..
        /// </summary>
        internal static string message_UserRegistrationSuccessful {
            get {
                return ResourceManager.GetString("message_UserRegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove User From Role Successful..
        /// </summary>
        internal static string message_UserRemoveFromRoleSuccessful {
            get {
                return ResourceManager.GetString("message_UserRemoveFromRoleSuccessful", resourceCulture);
            }
        }
    }
}
